### ISSUE TITLE
Theme color not applied 

### ISSUE THREAD

**Issue by oknozor** [aaranxu/adidoks#3]
First thanks for the great theme ! 

Seems changing the `theme_color` attribute under `config.toml` -> `[extra]` -> `theme_color` does not change anything. 
```toml
[extra]
theme_color = "#000"
``` 

I am missing something ?
